### ISSUE TITLE
Fileupload on Windows

### ISSUE THREAD

**Issue by Yoshi-E** [flagrow/upload#73]
- flagrow/upload extension version: 0.4.12
- flarum version: 0.1.0-beta.6
- Upload adapter causing issues: local: ^image\/.*
- Windows 10 x64 Operating System Version 10.0.14393
- Running XAMPP V3.2.2 (Running as Admin), XAMPP / PHP has no permission restrictions
- Local storage settings: Content Delivery URL (prefixes files): Empty

Incorrect URL Generated: "http://domain.eu/Forum/\assets/files\2017-04-05\1491391403-0-image.jpeg"
How the URL should look like: "http://domain.eu/Forum/assets/files/2017-04-05/1491391403-0-image.jpeg"

**Comment by Luceos** [comment]
This should have been fixed a while back. Not sure why it slipped.

**Comment by Yoshi-E** [comment]
Using latest version of both Flarum and upload, issue was still present, fixed it by adding:
"$file->url = str_replace('\\', '/', $file->url);" in [function "getDefaultMarkdownStringAttribute" ](https://github.com/flagrow/upload/blob/master/src/Commands/UploadHandler.php)
Not the best way, but at least it generates a correct url now
