### ISSUE TITLE
Re-add markdown support for directly showing images.

### ISSUE THREAD

**Issue by luceos** [flagrow/upload#90]
I have been working on a template branch that allows configuring the view template to be used per mime type. It's unfinished yet but would solve this. As we don't want to lose the proxy functionality we could temporarily create another solution by adding a toggle for "showing images inline, non proxied" and then using the "old" template. XSLT is quite easy just check the more complex blade templates.

**Comment by luceos** [comment]
Done in https://github.com/flagrow/upload/pull/97

**Comment by haydenjames** [comment]
I'm following a chain of references and duplicates, but still can't find where to disable this CSS that causes the image to be small and not full width of post.

**Comment by luceos** [comment]
Then perhaps you should wait for a reply on one of your questions?

See #102  and https://discuss.flarum.org/d/4154-flagrow-upload-the-intelligent-file-attachment-extension/370
